#version: "3"

services:
  pihole-unbound:
    container_name: pihole-unbound
    image: ghcr.io/hat3ph/pihole-unbound
    restart: unless-stopped
    hostname: pihole-unbound
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
      # optional to customize your own unbound settings
      #- './pi-hole.conf:/etc/unbound/unbound.conf.d/pi-hole.conf'
    ports:
      - 53:53/tcp # Pihole DNS connection
      - 53:53/udp # Pihole DNS connection
      - 80:80/tcp # Pihole web panel HTTP
      #- 443:443/tcp # Pihole web panel HTTPS
      #- 5335:5335/tcp # Uncomment to enable unbound access on local server
      #- 5335:5335/udp # Uncomment to enable unbound access on local server
    environment:
      - TZ=Asia/Kuala_Lumpur # set the correct timezone
      - FTLCONF_webserver_api_password=password # set your own web panel password
      - FTLCONF_dns_listeningMode=all # listen only to interface
      - FTLCONF_dns_upstreams=127.0.0.1#5335 # Use unbound as upstream DNS
      - TEMPERATUREUNIT=C # set preferred temperature unit
      - WEBTHEME=default-dark # web panel theme
      #- ADMIN_EMAIL=xxx@gmail.com # set your admin email address
